site_name: My Obsidian
docs_dir: ./Study Material
# theme: readthedocs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
repo_url: https://github.com/akshatmittal61/md-ssg/
repo_name: md-ssg
use_directory_urls: true
markdown_extensions:
  - smarty