site_name: My Obsidian
docs_dir: docs/
theme:
  name: material
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.sections
  - navigation.indexes
repo_url: https://github.com/akshatmittal61/md-ssg/
repo_name: md-ssg
use_directory_urls: true
markdown_extensions:
- pymdownx.arithmatex
- smarty
extra_javascript:
- https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
